#!/bin/sh

# Polkit (para reboot, poweroff, etc)
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Desactivar beep
xset -b

# Fondo de pantalla
feh --bg-scale ~/dev/suckless-btw/background.jpg &

#dwm blocks
#dwmblocks &

#slstatus
slstatus &

# Compositor (OBLIGATORIO para alpha)
picom &

# Window manager (SIEMPRE último)
exec dwm
